-- Migrasi 005: menaikkan level kesulitan bank soal jenjang SMA
-- (SE/WA/AN/GE/RA/ZR — jumlah & kode_soal tetap sama, isi diganti jadi versi
-- lebih sulit lewat UPDATE, bukan INSERT, supaya tidak duplikat), plus
-- menambah kategori baru BAKAT_AGM (Bakat Keagamaan: Tafsir/Hadis/Fiqih/Bahasa
-- Arab) untuk mengarahkan Tes Bakat Diferensial ke pemilihan mapel kelas XI
-- sesuai daftar resmi "Komponen Mapel Pendukung" sekolah.
--
-- Aman dijalankan berkali-kali: UPDATE menimpa baris yang sama, INSERT pakai
-- on conflict do nothing.

-- ============== SE (Melengkapi Kalimat) — SMA, versi lebih sulit ==============
update bank_soal set pertanyaan='Meskipun telah diberi bukti-bukti yang meyakinkan, ia tetap ... untuk mengubah pendiriannya.', pilihan='["bersedia","menolak","ragu","berusaha"]'::jsonb, jawaban_kunci='menolak', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_1';
update bank_soal set pertanyaan='Kebijakan tersebut menuai pro dan kontra karena dianggap ... kepentingan kelompok tertentu.', pilihan='["mengabaikan","mendukung","mengutamakan","menghambat"]'::jsonb, jawaban_kunci='mengutamakan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_2';
update bank_soal set pertanyaan='Bukan hanya berdampak pada sektor ekonomi, kebijakan itu juga ... stabilitas sosial masyarakat.', pilihan='["memperkuat","mengguncang","mengabaikan","melengkapi"]'::jsonb, jawaban_kunci='mengguncang', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_3';
update bank_soal set pertanyaan='Karena argumentasinya dibangun di atas asumsi yang keliru, kesimpulan yang diambilnya menjadi ... dipertahankan.', pilihan='["mudah","sulit","layak","penting"]'::jsonb, jawaban_kunci='sulit', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_4';
update bank_soal set pertanyaan='Alih-alih menyelesaikan konflik, mediator tersebut justru ... ketegangan di antara kedua pihak.', pilihan='["meredakan","memperuncing","mengabaikan","menengahi"]'::jsonb, jawaban_kunci='memperuncing', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_5';
update bank_soal set pertanyaan='Data yang disajikan tanpa konteks yang memadai berpotensi ... pembaca terhadap fakta yang sebenarnya.', pilihan='["mencerahkan","menyesatkan","meyakinkan","mengingatkan"]'::jsonb, jawaban_kunci='menyesatkan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_6';
update bank_soal set pertanyaan='Sikapnya yang selalu ... terhadap kritik membuat rekan-rekannya enggan memberikan masukan.', pilihan='["terbuka","defensif","reflektif","adaptif"]'::jsonb, jawaban_kunci='defensif', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_7';
update bank_soal set pertanyaan='Perusahaan itu terpaksa melakukan efisiensi besar-besaran akibat ... pendapatan yang berkepanjangan.', pilihan='["kenaikan","stagnasi","penyusutan","pemulihan"]'::jsonb, jawaban_kunci='penyusutan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_8';
update bank_soal set pertanyaan='Karena minim bukti pendukung, tuduhan tersebut akhirnya ... oleh pihak berwenang.', pilihan='["dibenarkan","dikuatkan","dimentahkan","disebarluaskan"]'::jsonb, jawaban_kunci='dimentahkan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_9';
update bank_soal set pertanyaan='Meski terkesan sepele, kelalaian kecil semacam itu dapat berakibat ... bagi keselamatan banyak orang.', pilihan='["fatal","ringan","wajar","biasa"]'::jsonb, jawaban_kunci='fatal', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_10';
update bank_soal set pertanyaan='Ia dikenal sebagai sosok yang selalu ... pendapat orang lain sebelum mengambil keputusan penting.', pilihan='["mengabaikan","mempertimbangkan","menyepelekan","menolak"]'::jsonb, jawaban_kunci='mempertimbangkan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_11';
update bank_soal set pertanyaan='Ketimbang mengakui kesalahannya, ia justru ... tanggung jawab kepada rekan setimnya.', pilihan='["memikul","melimpahkan","menerima","menanggung"]'::jsonb, jawaban_kunci='melimpahkan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_12';
update bank_soal set pertanyaan='Fenomena tersebut sulit dijelaskan secara ilmiah karena minimnya data yang dapat ....', pilihan='["diabaikan","diverifikasi","disangkal","diperdebatkan"]'::jsonb, jawaban_kunci='diverifikasi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_13';
update bank_soal set pertanyaan='Guru itu selalu berusaha ... materi yang rumit menjadi lebih mudah dipahami siswanya.', pilihan='["mempersulit","menyederhanakan","memperumit","mengaburkan"]'::jsonb, jawaban_kunci='menyederhanakan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_14';
update bank_soal set pertanyaan='Karena terlalu banyak intervensi dari pihak luar, proses negosiasi menjadi ... dan berlarut-larut.', pilihan='["lancar","efisien","berbelit-belit","singkat"]'::jsonb, jawaban_kunci='berbelit-belit', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_15';
update bank_soal set pertanyaan='Meskipun anggarannya terbatas, tim tersebut tetap berhasil ... target yang telah ditetapkan.', pilihan='["mengabaikan","mencapai","menunda","membatalkan"]'::jsonb, jawaban_kunci='mencapai', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_16';
update bank_soal set pertanyaan='Pernyataan yang disampaikan tanpa data pendukung cenderung dianggap ... oleh khalayak yang kritis.', pilihan='["meyakinkan","spekulatif","akurat","otentik"]'::jsonb, jawaban_kunci='spekulatif', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_17';
update bank_soal set pertanyaan='Karena reputasinya yang telah tercoreng, ia kesulitan untuk ... kembali kepercayaan publik.', pilihan='["menjaga","memulihkan","mempertahankan","meningkatkan"]'::jsonb, jawaban_kunci='memulihkan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_18';
update bank_soal set pertanyaan='Kebijakan yang diterapkan secara terburu-buru itu akhirnya ... berbagai masalah baru yang tak terduga.', pilihan='["mencegah","menimbulkan","menyelesaikan","meniadakan"]'::jsonb, jawaban_kunci='menimbulkan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_19';
update bank_soal set pertanyaan='Alih-alih memperkuat argumen utamanya, ia justru terjebak dalam detail-detail yang ....', pilihan='["relevan","substansial","tidak substansial","krusial"]'::jsonb, jawaban_kunci='tidak substansial', item_bank_version='2026-09-sma-hard-v3' where kode_soal='SE_sma_20';

-- ============== WA (Pemilihan Kata / ganjil-genap kelompok) — SMA, lebih sulit ==============
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Oksidasi","Reduksi","Netralisasi","Evaporasi"]'::jsonb, jawaban_kunci='Evaporasi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_1';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Sonet","Pantun","Syair","Prosa"]'::jsonb, jawaban_kunci='Prosa', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_2';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Nasionalisme","Patriotisme","Chauvinisme","Individualisme"]'::jsonb, jawaban_kunci='Individualisme', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_3';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Tundra","Taiga","Sabana","Estuari"]'::jsonb, jawaban_kunci='Estuari', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_4';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Isobar","Isoterm","Isohyet","Isotop"]'::jsonb, jawaban_kunci='Isotop', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_5';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Anabolisme","Katabolisme","Metabolisme","Metamorfisme"]'::jsonb, jawaban_kunci='Metamorfisme', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_6';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Monopoli","Oligopoli","Monopsoni","Deflasi"]'::jsonb, jawaban_kunci='Deflasi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_7';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Asimilasi","Akulturasi","Akomodasi","Disosiasi"]'::jsonb, jawaban_kunci='Disosiasi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_8';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Konveksi","Konduksi","Radiasi","Refraksi"]'::jsonb, jawaban_kunci='Refraksi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_9';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Interpelasi","Angket","Budget","Ratifikasi"]'::jsonb, jawaban_kunci='Ratifikasi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_10';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Introver","Ekstrover","Ambivert","Asertif"]'::jsonb, jawaban_kunci='Asertif', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_11';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Elastisitas","Plastisitas","Viskositas","Populasi"]'::jsonb, jawaban_kunci='Populasi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_12';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Epidermis","Dermis","Hipodermis","Epidemi"]'::jsonb, jawaban_kunci='Epidemi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_13';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Fauna","Flora","Biota","Geosfer"]'::jsonb, jawaban_kunci='Geosfer', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_14';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Hipotesis","Variabel","Populasi","Preposisi"]'::jsonb, jawaban_kunci='Preposisi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_15';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Simbiosis mutualisme","Simbiosis parasitisme","Simbiosis komensalisme","Adaptasi morfologi"]'::jsonb, jawaban_kunci='Adaptasi morfologi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_16';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Deduktif","Induktif","Silogisme","Deskriptif"]'::jsonb, jawaban_kunci='Deskriptif', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_17';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Autokrasi","Oligarki","Teokrasi","Birokrasi"]'::jsonb, jawaban_kunci='Birokrasi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_18';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Vokal rangkap","Diftong","Konsonan","Monoftong"]'::jsonb, jawaban_kunci='Konsonan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_19';
update bank_soal set pertanyaan='Manakah yang tidak sekelompok?', pilihan='["Resesi","Depresi ekonomi","Stagflasi","Stagnasi mental"]'::jsonb, jawaban_kunci='Stagnasi mental', item_bank_version='2026-09-sma-hard-v3' where kode_soal='WA_sma_20';

-- ============== AN (Analogi Verbal) — SMA, lebih sulit ==============
update bank_soal set pertanyaan='Aksioma : Teorema = Premis : ?', pilihan='["Argumen","Kesimpulan","Fakta","Data"]'::jsonb, jawaban_kunci='Kesimpulan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_1';
update bank_soal set pertanyaan='Antibodi : Antigen = Kunci : ?', pilihan='["Pintu","Gembok","Rumah","Gerbang"]'::jsonb, jawaban_kunci='Gembok', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_2';
update bank_soal set pertanyaan='Inflasi : Daya beli turun = Deflasi : ?', pilihan='["Daya beli turun","Daya beli naik","Harga naik","Produksi turun"]'::jsonb, jawaban_kunci='Daya beli naik', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_3';
update bank_soal set pertanyaan='Vaksin : Pencegahan = Antibiotik : ?', pilihan='["Pencegahan","Pengobatan","Diagnosis","Deteksi"]'::jsonb, jawaban_kunci='Pengobatan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_4';
update bank_soal set pertanyaan='Sentripetal : Menuju pusat = Sentrifugal : ?', pilihan='["Menuju pusat","Menjauhi pusat","Melingkar","Berputar"]'::jsonb, jawaban_kunci='Menjauhi pusat', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_5';
update bank_soal set pertanyaan='Oligarki : Segelintir orang = Monarki : ?', pilihan='["Rakyat","Satu orang","Banyak orang","Partai"]'::jsonb, jawaban_kunci='Satu orang', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_6';
update bank_soal set pertanyaan='Konkaf : Cekung = Konveks : ?', pilihan='["Cekung","Cembung","Datar","Lurus"]'::jsonb, jawaban_kunci='Cembung', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_7';
update bank_soal set pertanyaan='Nekrosis : Kematian sel akibat cedera = Apoptosis : ?', pilihan='["Kematian sel terprogram","Pembelahan sel","Pertumbuhan sel","Mutasi sel"]'::jsonb, jawaban_kunci='Kematian sel terprogram', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_8';
update bank_soal set pertanyaan='Barter : Tanpa uang = Kredit : ?', pilihan='["Tanpa uang","Pembayaran ditunda","Pembayaran tunai","Tanpa jaminan"]'::jsonb, jawaban_kunci='Pembayaran ditunda', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_9';
update bank_soal set pertanyaan='Amnesia : Kehilangan ingatan = Insomnia : ?', pilihan='["Kehilangan ingatan","Kesulitan tidur","Kehilangan nafsu makan","Gangguan bicara"]'::jsonb, jawaban_kunci='Kesulitan tidur', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_10';
update bank_soal set pertanyaan='Konduktor : Menghantarkan = Isolator : ?', pilihan='["Menghantarkan","Menghambat","Menyimpan","Melipatgandakan"]'::jsonb, jawaban_kunci='Menghambat', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_11';
update bank_soal set pertanyaan='Fusi nuklir : Penggabungan inti = Fisi nuklir : ?', pilihan='["Penggabungan inti","Pembelahan inti","Peluruhan radioaktif","Ionisasi"]'::jsonb, jawaban_kunci='Pembelahan inti', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_12';
update bank_soal set pertanyaan='Preseden : Kasus hukum sebelumnya = Referensi : ?', pilihan='["Kasus hukum sebelumnya","Sumber rujukan","Dokumen resmi","Bukti fisik"]'::jsonb, jawaban_kunci='Sumber rujukan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_13';
update bank_soal set pertanyaan='Xerofit : Tumbuhan gurun = Hidrofit : ?', pilihan='["Tumbuhan gurun","Tumbuhan air","Tumbuhan pegunungan","Tumbuhan pantai"]'::jsonb, jawaban_kunci='Tumbuhan air', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_14';
update bank_soal set pertanyaan='Otokrasi : Kekuasaan mutlak satu pihak = Anarki : ?', pilihan='["Kekuasaan mutlak satu pihak","Ketiadaan pemerintahan","Kekuasaan rakyat","Kekuasaan militer"]'::jsonb, jawaban_kunci='Ketiadaan pemerintahan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_15';
update bank_soal set pertanyaan='Metafora : Perbandingan implisit = Simile : ?', pilihan='["Perbandingan implisit","Perbandingan eksplisit","Pengulangan bunyi","Pertentangan makna"]'::jsonb, jawaban_kunci='Perbandingan eksplisit', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_16';
update bank_soal set pertanyaan='Endoterm : Suhu tubuh internal stabil = Ektoterm : ?', pilihan='["Suhu tubuh internal stabil","Suhu tubuh bergantung lingkungan","Tidak memiliki suhu tubuh","Suhu tubuh selalu tinggi"]'::jsonb, jawaban_kunci='Suhu tubuh bergantung lingkungan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_17';
update bank_soal set pertanyaan='Devaluasi : Penurunan nilai mata uang oleh pemerintah = Depresiasi : ?', pilihan='["Penurunan nilai mata uang oleh pemerintah","Penurunan nilai mata uang oleh mekanisme pasar","Kenaikan nilai mata uang oleh pemerintah","Kestabilan nilai mata uang"]'::jsonb, jawaban_kunci='Penurunan nilai mata uang oleh mekanisme pasar', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_18';
update bank_soal set pertanyaan='Litotes : Merendahkan secara berlebihan = Hiperbola : ?', pilihan='["Merendahkan secara berlebihan","Melebih-lebihkan","Menyindir halus","Membandingkan langsung"]'::jsonb, jawaban_kunci='Melebih-lebihkan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_19';
update bank_soal set pertanyaan='Adiabatik : Tanpa pertukaran kalor = Isotermal : ?', pilihan='["Tanpa pertukaran kalor","Suhu tetap konstan","Tekanan tetap konstan","Volume tetap konstan"]'::jsonb, jawaban_kunci='Suhu tetap konstan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='AN_sma_20';

-- ============== GE (Persamaan Kata) — SMA, lebih sulit ==============
update bank_soal set pertanyaan='Apa persamaan "Nekrosis" dan "Apoptosis"?', pilihan='["Jenis kematian sel","Jenis pembelahan sel","Jenis mutasi genetik","Jenis jaringan tubuh"]'::jsonb, jawaban_kunci='Jenis kematian sel', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_1';
update bank_soal set pertanyaan='Apa persamaan "Devaluasi" dan "Depresiasi"?', pilihan='["Penurunan nilai mata uang","Kenaikan nilai mata uang","Kebijakan fiskal","Kebijakan perdagangan"]'::jsonb, jawaban_kunci='Penurunan nilai mata uang', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_2';
update bank_soal set pertanyaan='Apa persamaan "Fusi nuklir" dan "Fisi nuklir"?', pilihan='["Reaksi yang melibatkan inti atom","Reaksi kimia biasa","Proses peluruhan zat radioaktif","Proses ionisasi gas"]'::jsonb, jawaban_kunci='Reaksi yang melibatkan inti atom', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_3';
update bank_soal set pertanyaan='Apa persamaan "Oligarki" dan "Plutokrasi"?', pilihan='["Sistem pemerintahan oleh sekelompok kecil elite","Sistem pemerintahan oleh rakyat","Sistem pemerintahan oleh militer","Sistem pemerintahan oleh agamawan"]'::jsonb, jawaban_kunci='Sistem pemerintahan oleh sekelompok kecil elite', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_4';
update bank_soal set pertanyaan='Apa persamaan "Metafora" dan "Simile"?', pilihan='["Majas perbandingan","Majas pertentangan","Majas sindiran","Majas penegasan"]'::jsonb, jawaban_kunci='Majas perbandingan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_5';
update bank_soal set pertanyaan='Apa persamaan "Xerofit" dan "Hidrofit"?', pilihan='["Klasifikasi tumbuhan berdasarkan habitat air","Klasifikasi tumbuhan berdasarkan cara berkembang biak","Jenis tumbuhan berbunga","Jenis tumbuhan berbiji tertutup"]'::jsonb, jawaban_kunci='Klasifikasi tumbuhan berdasarkan habitat air', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_6';
update bank_soal set pertanyaan='Apa persamaan "Adiabatik" dan "Isotermal"?', pilihan='["Proses termodinamika gas","Jenis gelombang bunyi","Sifat kemagnetan bahan","Hukum kekekalan massa"]'::jsonb, jawaban_kunci='Proses termodinamika gas', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_7';
update bank_soal set pertanyaan='Apa persamaan "Asimilasi" dan "Akulturasi"?', pilihan='["Proses sosial akibat percampuran budaya","Proses sosial yang bersifat memecah belah","Bentuk konflik antarkelompok","Bentuk penyimpangan sosial"]'::jsonb, jawaban_kunci='Proses sosial akibat percampuran budaya', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_8';
update bank_soal set pertanyaan='Apa persamaan "Konveksi" dan "Konduksi"?', pilihan='["Cara perpindahan kalor","Cara perambatan cahaya","Cara perambatan bunyi","Jenis gaya pada benda"]'::jsonb, jawaban_kunci='Cara perpindahan kalor', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_9';
update bank_soal set pertanyaan='Apa persamaan "Deduktif" dan "Induktif"?', pilihan='["Pola penalaran dalam menarik kesimpulan","Jenis paragraf naratif","Struktur teks eksposisi","Jenis majas dalam puisi"]'::jsonb, jawaban_kunci='Pola penalaran dalam menarik kesimpulan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_10';
update bank_soal set pertanyaan='Apa persamaan "Resesi" dan "Depresi ekonomi"?', pilihan='["Kondisi perlambatan/penurunan aktivitas ekonomi","Kondisi pertumbuhan ekonomi pesat","Kebijakan moneter ekspansif","Kebijakan fiskal ketat"]'::jsonb, jawaban_kunci='Kondisi perlambatan/penurunan aktivitas ekonomi', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_11';
update bank_soal set pertanyaan='Apa persamaan "Antiklin" dan "Sinklin"?', pilihan='["Struktur lipatan pada batuan akibat tenaga tektonik","Jenis batuan beku","Jenis patahan akibat gempa","Bentuk permukaan bumi akibat erosi"]'::jsonb, jawaban_kunci='Struktur lipatan pada batuan akibat tenaga tektonik', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_12';
update bank_soal set pertanyaan='Apa persamaan "Interpelasi" dan "Hak angket"?', pilihan='["Hak DPR dalam mengawasi pemerintah","Hak presiden dalam membuat kebijakan","Hak warga negara dalam pemilu","Hak yudikatif dalam mengadili"]'::jsonb, jawaban_kunci='Hak DPR dalam mengawasi pemerintah', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_13';
update bank_soal set pertanyaan='Apa persamaan "Epidermis" dan "Dermis"?', pilihan='["Lapisan penyusun kulit","Lapisan penyusun tulang","Jenis jaringan otot","Jenis sel darah"]'::jsonb, jawaban_kunci='Lapisan penyusun kulit', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_14';
update bank_soal set pertanyaan='Apa persamaan "Litotes" dan "Hiperbola"?', pilihan='["Majas yang melibatkan pernyataan tidak sesuai kenyataan","Majas pertentangan makna","Majas perbandingan langsung","Jenis rima dalam puisi"]'::jsonb, jawaban_kunci='Majas yang melibatkan pernyataan tidak sesuai kenyataan', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_15';
update bank_soal set pertanyaan='Apa persamaan "Isobar" dan "Isohyet"?', pilihan='["Garis pada peta yang menghubungkan titik dengan nilai sama","Jenis awan penyebab hujan","Skala pengukuran suhu udara","Alat pengukur curah hujan"]'::jsonb, jawaban_kunci='Garis pada peta yang menghubungkan titik dengan nilai sama', item_bank_version='2026-09-sma-hard-v3' where kode_soal='GE_sma_16';

-- ============== RA (Soal Hitungan) — SMA, lebih sulit (multi-langkah) ==============
update bank_soal set pertanyaan='Jika 3x − 7 = 2x + 5, maka nilai x adalah ....', pilihan='["10","11","12","13"]'::jsonb, jawaban_kunci='12', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_1';
update bank_soal set pertanyaan='Sebuah tangki berisi air sebanyak 3/5 dari kapasitasnya. Jika ditambahkan 40 liter, tangki menjadi penuh. Berapa kapasitas tangki?', pilihan='["80 liter","90 liter","100 liter","120 liter"]'::jsonb, jawaban_kunci='100 liter', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_2';
update bank_soal set pertanyaan='Harga sebuah baju setelah diskon 20% adalah Rp160.000. Berapa harga sebelum diskon?', pilihan='["Rp180.000","Rp190.000","Rp200.000","Rp210.000"]'::jsonb, jawaban_kunci='Rp200.000', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_3';
update bank_soal set pertanyaan='Dua kota A dan B berjarak 240 km. Mobil pertama berangkat dari A pukul 08.00 dengan kecepatan 60 km/jam, mobil kedua dari B pukul 08.00 menuju A dengan kecepatan 80 km/jam. Sekitar pukul berapa keduanya berpapasan?', pilihan='["09.30","09.43","09.50","10.00"]'::jsonb, jawaban_kunci='09.43', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_4';
update bank_soal set pertanyaan='Sebuah pekerjaan dapat diselesaikan oleh 8 orang dalam 15 hari. Jika pekerjaan itu harus selesai dalam 10 hari, berapa orang tambahan yang diperlukan (kecepatan kerja tiap orang sama)?', pilihan='["2 orang","3 orang","4 orang","5 orang"]'::jsonb, jawaban_kunci='4 orang', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_5';
update bank_soal set pertanyaan='Jika P(A)=0,5, P(B)=0,4, dan P(A∩B)=0,2, berapa P(A∪B)?', pilihan='["0,5","0,6","0,7","0,9"]'::jsonb, jawaban_kunci='0,7', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_6';
update bank_soal set pertanyaan='Suatu barisan geometri memiliki suku pertama 5 dan rasio 3. Berapa jumlah 4 suku pertamanya?', pilihan='["150","180","200","220"]'::jsonb, jawaban_kunci='200', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_7';
update bank_soal set pertanyaan='Sebuah toko memberi diskon 10%, lalu diskon tambahan 10% dari harga setelah diskon pertama. Jika harga awal Rp500.000, berapa harga akhirnya?', pilihan='["Rp390.000","Rp400.000","Rp405.000","Rp410.000"]'::jsonb, jawaban_kunci='Rp405.000', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_8';
update bank_soal set pertanyaan='Jika log 3 = 0,477, berapa nilai log 27? (log 27 = 3 log 3)', pilihan='["1,341","1,431","1,477","1,531"]'::jsonb, jawaban_kunci='1,431', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_9';
update bank_soal set pertanyaan='Rata-rata nilai 8 siswa adalah 75. Jika ditambahkan 2 siswa baru dengan nilai 90 dan 85, berapa rata-rata 10 siswa tersebut?', pilihan='["76,5","77","77,5","78"]'::jsonb, jawaban_kunci='77,5', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_10';
update bank_soal set pertanyaan='Sebuah kolam diisi pipa A dalam 6 jam dan pipa B dalam 12 jam (sendiri-sendiri). Jika kedua pipa dibuka bersamaan, berapa jam kolam terisi penuh?', pilihan='["3 jam","4 jam","5 jam","6 jam"]'::jsonb, jawaban_kunci='4 jam', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_11';
update bank_soal set pertanyaan='Segitiga siku-siku memiliki sudut 30° dan panjang sisi di depan sudut tersebut 5 cm. Berapa panjang sisi miringnya?', pilihan='["8 cm","9 cm","10 cm","12 cm"]'::jsonb, jawaban_kunci='10 cm', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_12';
update bank_soal set pertanyaan='Jika sebuah bilangan dikalikan 4 kemudian dikurangi 9 menghasilkan 39, berapa bilangan tersebut?', pilihan='["10","11","12","13"]'::jsonb, jawaban_kunci='12', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_13';
update bank_soal set pertanyaan='Penjualan sebuah perusahaan naik 20% pada tahun kedua, lalu turun 25% pada tahun ketiga (dari nilai tahun kedua). Jika penjualan tahun pertama Rp100 juta, berapa penjualan tahun ketiga?', pilihan='["Rp85 juta","Rp90 juta","Rp95 juta","Rp100 juta"]'::jsonb, jawaban_kunci='Rp90 juta', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_14';
update bank_soal set pertanyaan='Simpangan baku suatu data bernilai 4, dengan rata-rata 60. Berapa nilai yang berada tepat 2 simpangan baku di atas rata-rata?', pilihan='["64","66","68","70"]'::jsonb, jawaban_kunci='68', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_15';
update bank_soal set pertanyaan='Dua dadu dilempar bersamaan. Berapa peluang jumlah kedua mata dadu sama dengan 8?', pilihan='["4/36","5/36","6/36","7/36"]'::jsonb, jawaban_kunci='5/36', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_16';
update bank_soal set pertanyaan='Suatu barisan aritmetika memiliki suku ke-3 = 11 dan suku ke-7 = 27. Berapa beda barisan tersebut?', pilihan='["3","4","5","6"]'::jsonb, jawaban_kunci='4', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_17';
update bank_soal set pertanyaan='Modal Rp2.000.000 dibungakan secara majemuk 5% per tahun. Berapa nilai modal setelah 2 tahun?', pilihan='["Rp2.100.000","Rp2.150.000","Rp2.200.000","Rp2.205.000"]'::jsonb, jawaban_kunci='Rp2.205.000', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_18';
update bank_soal set pertanyaan='Jika 5 apel dan 3 jeruk berharga Rp37.000, sedangkan 3 apel dan 5 jeruk berharga Rp35.000, berapa harga 1 apel?', pilihan='["Rp4.000","Rp4.500","Rp5.000","Rp5.500"]'::jsonb, jawaban_kunci='Rp5.000', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_19';
update bank_soal set pertanyaan='Sebuah persegi panjang memiliki keliling 56 cm. Jika panjangnya 4 cm lebih besar dari lebarnya, berapa luas persegi panjang tersebut?', pilihan='["180 cm²","188 cm²","192 cm²","196 cm²"]'::jsonb, jawaban_kunci='192 cm²', item_bank_version='2026-09-sma-hard-v3' where kode_soal='RA_sma_20';

-- ============== ZR (Deret Angka) — SMA, lebih sulit (pola non-linear) ==============
update bank_soal set pertanyaan='1, 2, 4, 7, 11, 16, ?', pilihan='["20","21","22","23"]'::jsonb, jawaban_kunci='22', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_1';
update bank_soal set pertanyaan='2, 3, 5, 8, 13, 21, ?', pilihan='["30","32","34","36"]'::jsonb, jawaban_kunci='34', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_2';
update bank_soal set pertanyaan='1, 4, 9, 16, 25, ?', pilihan='["30","32","34","36"]'::jsonb, jawaban_kunci='36', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_3';
update bank_soal set pertanyaan='100, 95, 85, 70, 50, ?', pilihan='["20","25","30","35"]'::jsonb, jawaban_kunci='25', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_4';
update bank_soal set pertanyaan='3, 4, 7, 11, 18, 29, ?', pilihan='["40","44","47","50"]'::jsonb, jawaban_kunci='47', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_5';
update bank_soal set pertanyaan='2, 5, 11, 23, 47, ?', pilihan='["89","92","95","98"]'::jsonb, jawaban_kunci='95', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_6';
update bank_soal set pertanyaan='5, 6, 10, 19, 35, ?', pilihan='["55","58","60","64"]'::jsonb, jawaban_kunci='60', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_7';
update bank_soal set pertanyaan='81, 27, 9, 3, 1, ?', pilihan='["0","1/3","-1","1/2"]'::jsonb, jawaban_kunci='1/3', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_8';
update bank_soal set pertanyaan='1, 1, 2, 3, 5, 8, 13, ?', pilihan='["18","20","21","24"]'::jsonb, jawaban_kunci='21', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_9';
update bank_soal set pertanyaan='2, 6, 12, 20, 30, ?', pilihan='["36","40","42","45"]'::jsonb, jawaban_kunci='42', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_10';
update bank_soal set pertanyaan='4, 9, 19, 39, 79, ?', pilihan='["149","155","159","163"]'::jsonb, jawaban_kunci='159', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_11';
update bank_soal set pertanyaan='7, 10, 16, 28, 52, ?', pilihan='["94","98","100","104"]'::jsonb, jawaban_kunci='100', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_12';
update bank_soal set pertanyaan='1, 3, 6, 10, 15, 21, ?', pilihan='["26","27","28","30"]'::jsonb, jawaban_kunci='28', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_13';
update bank_soal set pertanyaan='2, 4, 8, 14, 22, 32, ?', pilihan='["40","42","44","46"]'::jsonb, jawaban_kunci='44', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_14';
update bank_soal set pertanyaan='200, 100, 150, 75, 125, ?', pilihan='["50","62,5","70","87,5"]'::jsonb, jawaban_kunci='62,5', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_15';
update bank_soal set pertanyaan='3, 5, 9, 17, 33, ?', pilihan='["61","63","65","67"]'::jsonb, jawaban_kunci='65', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_16';
update bank_soal set pertanyaan='1, 2, 6, 24, 120, ?', pilihan='["600","660","720","750"]'::jsonb, jawaban_kunci='720', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_17';
update bank_soal set pertanyaan='6, 11, 21, 41, 81, ?', pilihan='["151","155","161","165"]'::jsonb, jawaban_kunci='161', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_18';
update bank_soal set pertanyaan='90, 88, 84, 76, 60, ?', pilihan='["24","26","28","30"]'::jsonb, jawaban_kunci='28', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_19';
update bank_soal set pertanyaan='1, 5, 13, 29, 61, ?', pilihan='["115","120","125","130"]'::jsonb, jawaban_kunci='125', item_bank_version='2026-09-sma-hard-v3' where kode_soal='ZR_sma_20';

-- ============== BAKAT — kategori baru AGM (Keagamaan: Tafsir/Hadis/Fiqih/Bahasa Arab) ==============
-- Mengikuti pola BAKAT lain: jenjang 'semua', 10 item, urutan lanjut dari 50 -> 51..60.
insert into bank_soal (kode_soal, kategori, sub_kategori, jenjang, tipe, urutan, pertanyaan, pilihan, jawaban_kunci, meta, item_bank_version)
values ('BAKAT_AGM_51', 'BAKAT', 'AGM', 'semua', 'pilihan_tunggal', 51, 'Ilmu yang mempelajari penafsiran ayat-ayat Al-Qur''an disebut ilmu ....', '["Tafsir","Hadis","Fiqih","Nahwu"]'::jsonb, 'Tafsir', NULL, '2026-09-sma-hard-v3')
on conflict (kode_soal) do nothing;
insert into bank_soal (kode_soal, kategori, sub_kategori, jenjang, tipe, urutan, pertanyaan, pilihan, jawaban_kunci, meta, item_bank_version)
values ('BAKAT_AGM_52', 'BAKAT', 'AGM', 'semua', 'pilihan_tunggal', 52, 'Perkataan, perbuatan, dan ketetapan Nabi Muhammad ﷺ yang dijadikan sumber hukum disebut ....', '["Al-Qur''an","Hadis","Ijma''","Qiyas"]'::jsonb, 'Hadis', NULL, '2026-09-sma-hard-v3')
on conflict (kode_soal) do nothing;
insert into bank_soal (kode_soal, kategori, sub_kategori, jenjang, tipe, urutan, pertanyaan, pilihan, jawaban_kunci, meta, item_bank_version)
values ('BAKAT_AGM_53', 'BAKAT', 'AGM', 'semua', 'pilihan_tunggal', 53, 'Ilmu yang membahas hukum-hukum syariat berdasarkan dalil-dalil terperinci disebut ....', '["Fiqih","Tauhid","Akhlak","Balaghah"]'::jsonb, 'Fiqih', NULL, '2026-09-sma-hard-v3')
on conflict (kode_soal) do nothing;
insert into bank_soal (kode_soal, kategori, sub_kategori, jenjang, tipe, urutan, pertanyaan, pilihan, jawaban_kunci, meta, item_bank_version)
values ('BAKAT_AGM_54', 'BAKAT', 'AGM', 'semua', 'pilihan_tunggal', 54, 'Dalam ilmu hadis, rangkaian para perawi yang menyampaikan sebuah hadis disebut ....', '["Matan","Sanad","Rawi","Takhrij"]'::jsonb, 'Sanad', NULL, '2026-09-sma-hard-v3')
on conflict (kode_soal) do nothing;
insert into bank_soal (kode_soal, kategori, sub_kategori, jenjang, tipe, urutan, pertanyaan, pilihan, jawaban_kunci, meta, item_bank_version)
values ('BAKAT_AGM_55', 'BAKAT', 'AGM', 'semua', 'pilihan_tunggal', 55, 'Kata dalam bahasa Arab yang menunjukkan pekerjaan/perbuatan disebut ....', '["Isim","Fi''il","Harf","Dhamir"]'::jsonb, 'Fi''il', NULL, '2026-09-sma-hard-v3')
on conflict (kode_soal) do nothing;
insert into bank_soal (kode_soal, kategori, sub_kategori, jenjang, tipe, urutan, pertanyaan, pilihan, jawaban_kunci, meta, item_bank_version)
values ('BAKAT_AGM_56', 'BAKAT', 'AGM', 'semua', 'pilihan_tunggal', 56, 'Sumber hukum Islam yang berupa kesepakatan para ulama disebut ....', '["Ijma''","Qiyas","Istihsan","Urf"]'::jsonb, 'Ijma''', NULL, '2026-09-sma-hard-v3')
on conflict (kode_soal) do nothing;
insert into bank_soal (kode_soal, kategori, sub_kategori, jenjang, tipe, urutan, pertanyaan, pilihan, jawaban_kunci, meta, item_bank_version)
values ('BAKAT_AGM_57', 'BAKAT', 'AGM', 'semua', 'pilihan_tunggal', 57, 'Menganalogikan suatu masalah baru dengan hukum yang sudah ada karena kesamaan sebab disebut ....', '["Ijma''","Qiyas","Istishab","Maslahah"]'::jsonb, 'Qiyas', NULL, '2026-09-sma-hard-v3')
on conflict (kode_soal) do nothing;
insert into bank_soal (kode_soal, kategori, sub_kategori, jenjang, tipe, urutan, pertanyaan, pilihan, jawaban_kunci, meta, item_bank_version)
values ('BAKAT_AGM_58', 'BAKAT', 'AGM', 'semua', 'pilihan_tunggal', 58, 'Kitab tafsir klasik yang banyak dirujuk dalam kajian Al-Qur''an ditulis oleh ....', '["Imam Al-Ghazali","Ibnu Katsir","Imam Bukhari","Imam Syafi''i"]'::jsonb, 'Ibnu Katsir', NULL, '2026-09-sma-hard-v3')
on conflict (kode_soal) do nothing;
insert into bank_soal (kode_soal, kategori, sub_kategori, jenjang, tipe, urutan, pertanyaan, pilihan, jawaban_kunci, meta, item_bank_version)
values ('BAKAT_AGM_59', 'BAKAT', 'AGM', 'semua', 'pilihan_tunggal', 59, 'Ilmu yang mempelajari kaidah tata bahasa Arab dari sisi struktur kalimat (i''rab) disebut ....', '["Sharaf","Nahwu","Balaghah","Arudh"]'::jsonb, 'Nahwu', NULL, '2026-09-sma-hard-v3')
on conflict (kode_soal) do nothing;
insert into bank_soal (kode_soal, kategori, sub_kategori, jenjang, tipe, urutan, pertanyaan, pilihan, jawaban_kunci, meta, item_bank_version)
values ('BAKAT_AGM_60', 'BAKAT', 'AGM', 'semua', 'pilihan_tunggal', 60, 'Hukum mempelajari ilmu agama dasar yang menjadi kewajiban bagi setiap muslim disebut ....', '["Fardhu ''ain","Fardhu kifayah","Sunnah muakkad","Mubah"]'::jsonb, 'Fardhu ''ain', NULL, '2026-09-sma-hard-v3')
on conflict (kode_soal) do nothing;
